app1/urls.py
from django.urls import path
from app1 import views
app_name='app1'
urlpatterns=[
    path('register/',views.studentview,name='register'),
    path('read/',views.read,name='read'),
    path('update/',views.update,name='update'),
    path('update_value/<sid>/',views.update_value,name='update_value'),
]

app2/urls.py
from django.urls import path

app_name='app2'

from app2 import views
urlpatterns=[
path('create/',views.create,name='create'),
path('update/',views.update,name='update'),
path('updaterecord/ ',views.updaterecord,name='updaterecord'),
]

app3/urls.py
from django.urls import path
from app3 import views
app_name='app3'
urlpatterns=[
 path('reg/',views.userview,name='reg'),
 path('login/',views.loginview,name='login'),
 path('homepage/',views.homepage,name='homepage'),
 path('logout/',views.logout_view, name='logout'),
]

pro1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('app3/',include('app3.urls')),
]

app1/models.py
from django.db import models

# Create your models here.
class studentmodel(models.Model):
    stu_id=models.CharField(max_length=20,primary_key=True)
    name=models.CharField(max_length=25)
    email=models.EmailField()
    phone=models.PositiveBigIntegerField()
    location=models.CharField(max_length=30)
    

app2/models.py
from django.db import models

# Create your models here.
class usermodel(models.Model):
    name=models.CharField(max_length=30)
    email=models.EmailField()
    phone=models.PositiveBigIntegerField()

app3/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User,AbstractUser

# Create your models here.
class studentmodel(User):
    
    
    phone=models.PositiveBigIntegerField()
    gender=models.CharField(max_length=25,choices=[['male','Male'],['female','Female']])

app1/forms.py
from django import forms

from app1.models import studentmodel


class studentform(forms.Form):
    stu_id=forms.CharField()
    name=forms.CharField(widget=forms.TextInput)
    email=forms.EmailField(widget=forms.EmailInput)
    phone=forms.IntegerField()
    location=forms.CharField(widget=forms.TextInput)

app3/forms.py
from django import forms

from app3.models import studentmodel
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.hashers import  make_password
class userform(UserCreationForm):
    password2=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=studentmodel
        fields=['username','first_name','last_name','email','phone','gender','password']
    def save(self,commit=True):
        user=super(userform,self).save(commit=False)
        user.password=make_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

app1/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from app1.models import studentmodel

from app1.forms import studentform
# Create your views here.
def studentview(request):
    form=studentform()
    if request.method=='POST':
        form=studentform(request.POST)
        if form.is_valid():
            stu_id=request.POST['stu_id']
            name=request.POST['name']
            email=request.POST['email']
            phone=request.POST['phone']
            loc=request.POST['location']
            p=studentmodel.objects.create(stu_id=stu_id,name=name,email=email,phone=phone,location=loc)
        return redirect('/app1/read/')
    return render(request,'student.html', {'form':form})

def read(request):
    data=studentmodel.objects.all().values()
    

    return render(request,'read.html',{'data':data})
def update(request):
    if request.method=='POST':
        sid= request.POST['sid']
        res=studentmodel.objects.filter(stu_id=sid)
        return render(request,'update.html',{'res':res})
    return render(request,'update.html')

def update_value(request,sid):
    if request.method=="POST":
        name =request.POST['name']
        email= request.POST['email']
        phone= request.POST['phone']
        location=request.POST['location']
        print(name,email,phone,location)
        res=studentmodel.objects.filter(stu_id=sid).update(name=name,email=email,phone=phone,location=location)
        #return HttpResponse('update')
        return redirect('/app1/register/')
    return render(request,'insert.html')

app2/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages

from app2.models import usermodel
# Create your views here.
def create(request):
    if request.method=='POST':
        name=request.POST['username']
        email=request.POST.get('email')
        phone=request.POST['tel']
        usermodel.objects.create(name=name,email=email,phone=phone)

        messages.success(request, f'registration successfull {name}')
    return render(request,'index.html')

def update(request):
    
    if request.method=='POST':
        print(request.POST['value'])
        
        res=usermodel.objects.get(name=request.POST['value'])
        return render(request,'update1.html',{'res':res,'temp':True})
        # else:
        #     pk=request.POST['id']
        #     name=request.POST['username']
        #     email=request.POST.get('email')
        #     phone=request.POST['tel']
        #     usermodel.objects.filter(id=pk).update(name=name,email=email,phone=phone)
        #     return HttpResponse('data has been updated')

    res=usermodel.objects.all()
    return render(request,'update1.html',{'res':res,'temp':False})

def updaterecord(request):
    pk=request.POST['id']
    name=request.POST['username']
    email=request.POST.get('email')
    phone=request.POST['tel']
    usermodel.objects.filter(id=pk).update(name=name,email=email,phone=phone)
    return HttpResponse('data has been updated')

app3/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from app3.forms import userform
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.
def userview(request):
    form=userform()
    if request.method=='POST':
        form=userform(request.POST)
        
        if form.is_valid():
            form.save()
            return HttpResponse('register')
    return render(request,'reg.html',{'form':form})


def loginview(request):
    form=AuthenticationForm()
    if request.method=='POST':
        form=AuthenticationForm(request,request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("/app3/homepage/")
            else:
                messages.error(request, "Invalid username or password.")
                # messages= messages.get_messages(request)
        else:
            messages.error(request, "Invalid username or password.")
            # messages= messages.get_messages(request)
    return render(request,'login.html',{'form':form})

@login_required(login_url='/app3/login/')
def homepage(request):
    return render(request,'home.html')

def logout_view(request):
    logout(request)
    messages.success(request,"logout successfully")
    # messages= messages.get_messages(request)
    return redirect('/app3/reg/')

app1/templates/insert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <input type="text" id="id_sname" name="name" required><br>
        <input type="email" id="id_marks" name="email" required><br>
        <input type="phone" id="id_doj" name="phone" required><br>
        <input type="text" id="id_loc" name="loc" required><br>
        <input type="submit" value="insert">
        </form>

        <a href="{% url 'app1:register' %}"><button>select</button></a>
</body>
</html>

app1/templates/read.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{data}}
        
    </form>
</body>
</html>

app1/templates/student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="register">
    </form>
</body>
</html>

app1/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% if res %}
    {%for i in res%}
    <form method="post" >
        
        {% csrf_token %}
        <input type="text" id="id_sname" name="name" value="{{i.name}}" required><br>
        <input type="email" id="id_marks" name="email" value="{{i.email}}"required><br>
        <input type="phone" id="id_doj" name="phone" value="{{i.phone}}" required><br>
        <input type="text" id="id_loc" name="location" value="{{i.location}}" required><br>
        <input type="submit" value="update_val">
        </form>
        {% endfor %}
    {% else %}
    <form method="post">
        {% csrf_token %}
        <input type="text" id="id_sid" name="sid" required><br>
        <input type="submit" value="update">
        </form>
    {% endif  %}
</body>
</html>

app2/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for msg in messages %}
    <h1>{{msg}}</h1>
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        <label for="user">user</label>
        <input type="text" id="user" name="username" placeholder="username">
        <label for="email">email</label>
        <input type="email" id="email" name="email" placeholder="email">
        <label for="tel">tel</label>
        <input type="tel" id="tel" name="tel" placeholder="tel">
        <input type="submit" value="signin">
    </form>
</body>
</html>

app2/templates/upd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action='{% url "app2:update" pk= %}' method="post">
        {% csrf_token %}
        <input list="values" name="value">
        <datalist id="values">
            {% for i in res %}
            <option value="{{i.name}}">{{i.name}}</option>
            {% endfor %}

        </datalist>
        <input type="submit" value="update">
    </form>
</body>
</html>

app2/templates/update1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{temp}}
    {% if temp %}

    <form action="{% url 'app2:updaterecord' %}" method="post">
        {% csrf_token %}
        <label for="id">id</label>
        <input type="text" id="user" name="id" placeholder="id" value="{{res.id}}" readonly >
        <label for="user">user</label>
        <input type="text" id="user" name="username" placeholder="username" value="{{res.name}}" >
        <label for="email">email</label>
        <input type="email" id="email" name="email" placeholder="email" value="{{res.email}}">
        <label for="tel">tel</label>
        <input type="tel" id="tel" name="tel" placeholder="tel" value="{{res.phone}}">
        <input type="submit" value="update">

    </form>
    {% else %}
    <form method="post">
        {% csrf_token %}
        <input list="values" name="value">
        <datalist id="values">
            {% for i in res %}
            <option value="{{i.name}}">{{i.name}}</option>
            {% endfor %}

        </datalist>
        <input type="submit" value="update">
    </form>
    {% endif %}
</body>
</html>

app3/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'app3:reg'%}">register page</a>
    <a href="{% url 'app3:logout' %}">logout</a>
</body>
</html>

app3/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method='post'>
        {% csrf_token %}

        {{form.as_p}}
        <button type="submit">Register</button>
    </form>
</body>
</html>

app3/templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for msg in messages %}
    {{msg}}
    {%endfor%}
    <form action="" method='post'>
        {% csrf_token %}

        {{form.as_p}}
        <button type="submit">Register</button>
    </form>
    <a href="{% url 'app3:login' %}">login</a>
</body>
</html>